---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
    strings:
      - TODO
      - FIXME
      - HACK
      - BUG
  nodesecurity:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
exclude_paths:
- dist/**/*
- test/**/*
