language: node_js
node_js:
  - "4.2.3"
  - "4"
  - "0.12"
  - "0.10"
install:
  - npm install
script:
  - npm run check
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
